### ISSUE TITLE
2024.03.1 and 2024.06.0 releases are broken

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/ACCESS-OM2-BGC#13]
`access-om2-bgc 2024.03.1` and `access-om2-bgc 2024.06.0` are built with `hdf5 1.14.3` which contains [a bug](https://github.com/HDFGroup/hdf5/issues/3831) that prevents ACCESS-OM2-BGC from running.

The issue [is fixed](https://github.com/HDFGroup/hdf5/pull/3837) in `hdf5 1.14.4`, but this version [is not yet available in the spack package](https://github.com/spack/spack/blob/ae2f6261689ee1e70b621bf29f2d0f6810b6b309/var/spack/repos/builtin/packages/hdf5/package.py).

What's the right way forward here? Revert to `hdf5 1.14.2` for now?

Note, this issue also affects one ACCESS-OM2 release - see https://github.com/ACCESS-NRI/ACCESS-OM2/issues/74

## Tasks
 - [x] Remove `access-om2-bgc 2024.03.1` as a Release (but keep the tag for transparency)
 - [x] Remove `access-om2-bgc 2024.06.0` as a Release (but keep the tag for transparency)
 - [x] Create the (first!) `backport/2024.03` branch, which is where the `2024.03.*` (namely, `2024.03.2`) tags will live, since there is a `2024.06.0` in front in the history. 
 - [x] Link PR for `2024.03.2` that addresses the above
 - [x] Link PR for `2024.06.1` that addresses the above (can be main branch)

**Comment by CodeGat** [comment]
Note: We have released a `ACCESS-OM2-BGC 2024.07.0` that contains just the MOM5 WOMBAT bug fix. The above can still be done.

**Comment by CodeGat** [comment]
Closing this due to archiving of the repository. We had ended up pulling these releases.
